# Generated by Django 4.2.20 on 2025-04-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'корзину', 'verbose_name_plural': 'Корзина'},
        ),
    ]
